### ISSUE TITLE
.container.lightning.com's server IP address could not be found.

### ISSUE THREAD

**Issue by alexleventer** [developerforce/LightningContainerExamples#15]
I wasn't able to get the Basic or ApexController example working. I see the following after following the provided instructions:

![image](https://user-images.githubusercontent.com/3254549/37262895-dbe930de-2562-11e8-8178-f1f461482e44.png)

**Comment by mpsenn** [comment]
It appears the DNS records for your org were not correctly created. If you open a ticket with support, they have an internal "scrutiny" they can run to fix this up.

Did you recently configure My Domain for this org? I don't know why this issue happened.

**Comment by alexleventer** [comment]
Thanks @mpsenn - ticket submitted. I'll let you know what i end up hearing back. 

I configured My Domain right before I set up your demos.

I'm going to go ahead and close out this issue (b/c it is on my end).

**Comment by mpsenn** [comment]
Thanks Alex. I've seen it take 10 minutes to create the DNS records. Any longer, there's probably an issue on the Salesforce side.

**Comment by Ishitaver** [comment]
I am getting same error..did you find the solution for the same
