### ISSUE TITLE
LCC.callApex not working. I am not getting any callback.

### ISSUE THREAD

**Issue by tusharbudhe0302** [developerforce/LightningContainerExamples#19]
`  callApex() {
    console.log('ReactcallApex');
    LCC.callApex("ApexController.getAccount",
      this.state.name,
      this.handleAccountQueryResponse,
      { escape: true });
  }

  handleAccountQueryResponse(result, event) {
    console.log('handleAccountQueryResponse : ' + result);
    if (event.status) {
      this.setState({ account: result });
    }
    else if (event.type === "exception") {
      console.log(event.message + " : " + event.where);
    }
  }
`

**Comment by ennoucas** [comment]
Have you added a **manifest.json** file in your static resource ? You need to declare your apex controller otherwise Salesforce is blocking the access and unfortunately does not give any errors... Here is the template you should use : 
`{
  "landing-pages" : [
      {
          "path": "index.html",
          "apex-controller": "ApexController"
      }
  ]
}`

**Comment by rahulmalhotra** [comment]
Hi @tusharbudhe0302 
I was facing the same error but as @ennoucas told, you need to add this thing in the manifest.json of your production build, so try updating the manifest.json in the production build by adding this and then upload your static resource. Hope it helps..!!

**Comment by tusharbudhe0302** [comment]
It's helped me. Thanks, guys.
