### ISSUE TITLE
net::ERR_INSECURE_RESPONSE Loading LCC?

### ISSUE THREAD

**Issue by afawcett** [developerforce/LightningContainerExamples#3]
Hi @dougdew, my pre-release is giving me some new errors today, any ideas? (nothing has changed in it since we last spoke). There are many errors, but the first is loading the LCC content itself with a net::ERR_INSECURE_RESPONSE.

![screen shot 2017-05-28 at 12 57 36](https://cloud.githubusercontent.com/assets/1167760/26531791/bb6c7b3a-43a5-11e7-8fee-bd3421a9ddb3.png)

**Comment by afawcett** [comment]
Also, wondering what you make of this discussion, its a simpler (and thus preferred means) to consume the Streaming API, but depends on the LC Session ID? Which per my comments on the issue, https://github.com/mshanemc/liveRecord/issues/1, i am not sure if its a feature or bug that it works?

**Comment by afawcett** [comment]
Ok, my bad it looks like i had a corrupted static resource.

**Comment by dougdew** [comment]
@afawcett Sorry for the late reply. I'm on vacation.

The net::ERR_INSECURE_RESPONSE error was most likely due to a certificate error that was due to the certificates not yet being deployed for the new container.lightning.com domain.
